### PR TITLE
rootless: don't create a namespace unless for containers-storage

### LINKED ISSUE #649: Skopeo now requires capabilities when executed as regular user
It uses to work fine in bubblewrap to copy image between registry but it no longer do:

```
$ ./skopeo --version
skopeo version 0.1.36-dev commit: 904b064da44eecfeea57f2c935e230fd41574ac8
$ bwrap  --unshare-all --bind / / --proc /proc --dev dev /bin/bash
$ ./skopeo copy docker-daemon:test:latest docker-daemon:test:test
Error: error writing "allow" to setgroups: write /proc/33/setgroups: operation not permitted
ERRO[0000] error opening "allow" to /proc/33/setgroups: write /proc/33/setgroups: operation not permitted 
ERRO[0000] (unable to determine exit status)   

$ bwrap --cap-add CAP_CHOWN --cap-add CAP_DAC_OVERRIDE --cap-add CAP_FOWNER --cap-add CAP_FSETID --cap-add CAP_MKNOD --cap-add CAP_SETFCAP --unshare-all --bind / / --proc /proc --dev dev /bin/bash
$ ./skopeo copy docker-daemon:test:latest docker-daemon:test:test
OK
```

Shouldn't the tool checks if the capabilities are really needed before requiring them (e.g. when doing remote copies)?

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change fixes skopeo usage in restricted environment such as
bubblewrap where it doesn't need extra capabilities or user namespace
to perform its action.

Close #649

Signed-off-by: Tristan Cacqueray <tdecacqu@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
This looks like a clever solution to me. @giuseppe PTAL

**Comment by giuseppe** [comment]
thanks for the patch!  Yes, I think it is a good fix, and should also address https://github.com/containers/skopeo/issues/652

**Comment by TristanCacqueray** [comment]
You're welcome, thank you for the prompt review. FWIW I tried using a cleaner method (such as alltransports.ParseImageName) but I couldn't find the right predicate to test for containers-storage type. The proposed solution assumes all the containers-storage image reference start with the `containers-storage:` prefix.

**Comment by giuseppe** [comment]
@mtrmac is there any cleaner way to test that?  Are you fine with this approach?

**Comment by vrothberg** [comment]
One way could be to use `ref, err := ParseImageName(...)` and if `err == nil` to compare `ref.Transport().Name() == storage.Transport.Name()`.

**Comment by TristanCacqueray** [comment]
The issue with ParseImageName is that it may fail early with `chown /home/fedora/.local/share/containers/storage/vfs: operation not permitted`

**Comment by vrothberg** [comment]
Ouch, sorry for missing that. In this case, we can mimic what `ParseImageName(...)` effectively does:
```golang
parts := strings.SplitN(imgName, ":", 2)
if len(parts) != 2 {
   continue
}
if parts[0] == storage.Transport.Name() { // we have storage reference (but can't validate it yet) }
```

**Comment by TristanCacqueray** [comment]
Done, thank you for the suggestion.

**Comment by rhatdan** [comment]
LGTM
Although I still want @mtrmac to chime in.

**Comment by mtrmac** [comment]
> The issue with ParseImageName is that it may fail early with `chown /home/fedora/.local/share/containers/storage/vfs: operation not permitted`

Oh, wow. That’s… a mess.

@nalind AFAICS this is essentially because `storageTransport.ParseStoreReference` needs a working `store` so that it can support image ID prefixes:
```go
if img, err := store.Image(possibleID); err == nil && img != nil && len(possibleID) >= minimumTruncatedIDLength && strings.HasPrefix(img.ID, possibleID)
```
and the like.  Is there any chance we could drop that functionality? (I guess not, but it would make dealing with this in callers so much simpler.)

Alternatively, would it be reasonably possible for `c/storage.GetStore` to return a typed error indicating that “this would work in a user namespace”?

File: cmd/skopeo/utils.go [hunk 1]
```diff
@@ -16,8 +17,18 @@ type errorShouldDisplayUsage struct {
 	error
 }
 
+// Check if container-storage are used before doing the maybeReexec
 func needsRexec(c *cli.Context) error {
-	return maybeReexec()
+	for _, arg := range c.Args() {
+		parts := strings.SplitN(arg, ":", 2)
+		if len(parts) != 2 {
```
Comment (mtrmac) [inline cmd/skopeo/utils.go]: If we are going to do this, let’s add a `c/image/transports.TransportFromImageName` (which returns a `types.ImageTransport`) instead of hard-coding it in skopeo.

File: cmd/skopeo/utils.go [hunk 2]
```diff
@@ -16,8 +17,18 @@ type errorShouldDisplayUsage struct {
 	error
 }
 
+// Check if container-storage are used before doing the maybeReexec
 func needsRexec(c *cli.Context) error {
-	return maybeReexec()
+	for _, arg := range c.Args() {
```
Comment (mtrmac) [inline cmd/skopeo/utils.go]: This is _way_ too imprecise.  Instead:
- In the various commands, drop `Before: needsReexec`
- In each of the command handlers, run something like `maybeReexec(inputParameter)` _only for the relevant parameters_, something like:
    ```go
        inputImageName := image.args[0]
        if err := maybeReexec(inputImageName); err != nil { 
           return err
        }
    	… := parseImageSource(ctx, opts.image, inputImage) // or parseImage or alltransports.ParseImageName
    ```
    possibly rearranging this so that the `maybeReexec`s happen at the start of the command handlers, before any other real work gets done.

File: cmd/skopeo/utils.go [hunk 3]
```diff
@@ -16,8 +17,18 @@ type errorShouldDisplayUsage struct {
...
+		parts := strings.SplitN(arg, ":", 2)
+		if len(parts) != 2 {
+			continue
+		}
+		if parts[0] == storage.Transport.Name() {
```
Comment (mtrmac) [inline cmd/skopeo/utils.go]: (This could, in principle, be a `transport.RequiresReexecInUserNamespace()` or something like that, but ultimately we are the use of `github.com/containers/`**`storage`**`/pkg/reexec`, so that wouldn’t make the code any more general.)

**Comment by fungi** [comment]
Just for another data point, we're temporarily running with a16489e applied in production and it seems to have solved #649 for us. Thanks @TristanCacqueray!

**Comment by TristanCacqueray** [comment]
@mtrmac Thank you for the suggestions, I think the last change implements them along with https://github.com/containers/image/pull/631 for the TransportFromImageName procedure. Not sure what is the policy around vendoring thus I inlined the c/image change in that PR.

As @fungi mentioned, the opendev.org infrastructure is using a continuously built version of skopeo which triggered the issue of using reexec in unprivileged environment like bubblewrap.

File: cmd/skopeo/copy.go [hunk 4]
```diff
@@ -87,6 +86,10 @@ func (opts *copyOptions) run(args []string, stdout io.Writer) error {
 		return errorShouldDisplayUsage{errors.New("Exactly two arguments expected")}
 	}
 
+	if err := needReexec(args); err != nil {
```
Comment (mtrmac) [inline cmd/skopeo/copy.go]: This works, but it’s still non-obvious that this is tied with the `args[…]` uses elsewhere. Please use actual variables,  like in https://github.com/containers/skopeo/pull/653#discussion_r284781828 , so that the `args`→image name “semantic conversion” happens at exactly one place. (IOW, so that we can, e.g. rip out and replace the CLI framework without changing the logic at all.)

File: cmd/skopeo/layers.go [hunk 5]
```diff
@@ -45,6 +44,12 @@ func (opts *layersOptions) run(args []string, stdout io.Writer) (retErr error) {
 		return errors.New("Usage: layers imageReference [layer...]")
 	}
 
+	imageNames := make([]string, 1)
+	imageNames[0] = args[0]
+	if err := needReexec(imageNames); err != nil {
```
Comment (mtrmac) [inline cmd/skopeo/layers.go]: This would be easier to read/write with a
```go
func needReexec(imageNames ...string)
```
; no need to have an array, or artificially manufacture it, in the callers.

File: cmd/skopeo/unshare_linux.go [hunk 6]
```diff
@@ -32,3 +34,13 @@ func maybeReexec() error {
 	}
 	return nil
 }
+
+func needReexec(imageNames []string) error {
```
Comment (mtrmac) [inline cmd/skopeo/unshare_linux.go]: (Now that this is being revisited: `needReexec` sounds as if it is returning a boolean.  I can’t think of a _good_ replacement but at least a cumbersome `reexecIfNecessaryForImages` would 1) clearly indicate an action, and 2) explain the obscure thing we are dealing with, for future readers who will have no idea that this is necessary and why. Or maybe some simpler name, with a doc string that clearly describes what is going on.)

File: cmd/skopeo/copy.go (hunk 4 above)
Comment (TristanCacqueray) [reply cmd/skopeo/copy.go]: Done

File: cmd/skopeo/layers.go (hunk 5 above)
Comment (TristanCacqueray) [reply cmd/skopeo/layers.go]: Thanks for the suggestion (i didn't know golang had varargs... :).

File: cmd/skopeo/unshare_linux.go (hunk 6 above)
Comment (TristanCacqueray) [reply cmd/skopeo/unshare_linux.go]: Next commit uses the cumbersome name so that it embed the action purpose for the caller.

File: cmd/skopeo/copy.go [hunk 7]
```diff
@@ -86,20 +85,25 @@ func (opts *copyOptions) run(args []string, stdout io.Writer) error {
 	if len(args) != 2 {
 		return errorShouldDisplayUsage{errors.New("Exactly two arguments expected")}
 	}
+	imageNames := args
+
+	if err := reexecIfNecessaryForImages(imageNames...); err != nil {
```
Comment (mtrmac) [inline cmd/skopeo/copy.go]: (Sigh… fine :) )

File: vendor.conf [hunk 8]
```diff
@@ -2,7 +2,7 @@
 github.com/urfave/cli v1.20.0
 github.com/kr/pretty v0.1.0
 github.com/kr/text v0.1.0
-github.com/containers/image ff926d3c79684793a2135666a2cb738f44ba33dc
+github.com/containers/image 2d92e2533d517b6db4ae7d085a332915fec57867
```
Comment (mtrmac) [inline vendor.conf]: That commit does not actually exist yet, which would make `make vendor` not reproducible.  After https://github.com/containers/image/pull/631 is merged, please update this with the actual merge commit and re-vendor.

Comment (TristanCacqueray) [reply vendor.conf]: done

**Comment by mtrmac** [comment]
LGTM. Thanks!
